<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Starlight_Translate_Instalador</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>img\icon-app\Sophie.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="img\**\*.*" />
  </ItemGroup>

</Project>